name: Build & Release Firmware

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Instalar GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'

      - name: Executar GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Substituir token de versão no código
        run: |
          VERSION=${{ steps.gitversion.outputs.semVer }}
          echo "🔁 Substituindo versão para $VERSION"
          sed -i "s|#{Deploy_Version}#|$VERSION|" src/main.cpp

      - name: Compilar firmware
        run: pio run

      - name: Renomear firmware final
        run: |
          mkdir firmware
          cp .pio/build/esp32dev/firmware.bin firmware/retrorelay-${{ steps.gitversion.outputs.semVer }}.bin

      - name: Criar release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          files: firmware/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
